# Generated by Django 2.2.6 on 2019-10-16 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danh_sach_lop',
            name='ten_lop_khong_dau',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mon_hoc',
            name='ten_mon_khong_dau',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
