# Generated by Django 2.2.6 on 2019-11-03 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0002_auto_20191016_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binh_luan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='danh_gia',
            name='date',
        ),
        migrations.AddField(
            model_name='binh_luan',
            name='ngay_tao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='danh_gia',
            name='ngay_tao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='danh_sach_lop',
            name='id_mon_hoc',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='tutor_app.Mon_hoc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danh_sach_lop',
            name='ngay_tao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mon_hoc',
            name='ngay_tao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='phu_huynh',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='so_lien_lac',
            name='ngay_tao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gia_su',
            name='ngay_tao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Lop_yeu_cau',
            fields=[
                ('id_lop', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('trang_thai', models.CharField(choices=[('0', 'Chua xac thuc'), ('1', 'Da xac thuc')], max_length=20)),
                ('mo_ta', models.TextField()),
                ('hinh_thuc_day', models.CharField(max_length=150)),
                ('yeu_cau_gioi_tinh', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
                ('ghi_chu', models.TextField()),
                ('so_buoi_hoc', models.IntegerField()),
                ('ngay_tao', models.DateField(default=django.utils.timezone.now)),
                ('id_gia_su', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_app.Gia_su')),
                ('id_mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_app.Mon_hoc')),
                ('id_phu_huynh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_app.Phu_huynh')),
            ],
        ),
    ]
